runtime: nodejs10
service: default

instance_class: F1
automatic_scaling:
    max_instances: 1

handlers:
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: build/\1
  upload: build/(.*\.js)
  http_headers:
    Access-Control-Allow-Origin: "*"
    
- url: /
  static_files: build/index.html
  upload: build/index.html
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
  http_headers:
    Access-Control-Allow-Origin: "*"
