runtime: nodejs10
service: default

handlers:
- url: /(.*\.js)
  mime_type: text/javascript
  static_files: build/\1
  upload: build/(.*\.js)

- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
